# Simple name-to-gender mapping (you can expand this)
MALE_NAMES = {
    'john', 'james', 'robert', 'michael', 'william', 'david', 'richard', 'joseph',
    'thomas', 'christopher', 'charles', 'daniel', 'matthew', 'anthony', 'mark',
    'donald', 'steven', 'paul', 'andrew', 'joshua', 'kenneth', 'kevin', 'brian',
    'george', 'edward', 'ronald', 'timothy', 'jason', 'jeffrey', 'ryan', 'jacob',
    'gary', 'nicholas', 'eric', 'jonathan', 'stephen', 'larry', 'justin', 'scott',
    'brandon', 'benjamin', 'samuel', 'gregory', 'frank', 'raymond', 'alexander',
    'patrick', 'jack', 'dennis', 'jerry', 'tyler', 'aaron', 'jose', 'henry',
    'adam', 'douglas', 'nathan', 'peter', 'zachary', 'kyle', 'noah', 'alan',
    'ethan', 'jeremy', 'lionel', 'wayne', 'arthur', 'mason', 'roy', 'ralph',
    'eugene', 'louis', 'philip', 'bobby', 'zvi', 'stuart', 'florian', 'chris', 
    'christian', 'kaj', 'gleb', 'robin', 'anders', 'phil', 'stefan', 'jonah',
    'gunnar', 'abram', 'so8res', 'eliezer', 'soeren', 'aris', 'turchin', 'trevor',
    'habryka', 'rohin', 'turntrout', 'neel', 'evhub', 'bill', 'zack', 'johannes',
    'marius', 'jan', 'holden', 'arjun', 'jsteinhardt', 'buck', 'davis', 'bogdan',
    'duncan', 'evan', 'esben', 'quintin', 'dmitry', 'leo', 'yoav', 'mike', 'rudi',
    'martin', 'roger', 'owen', 'spencer', 'garrison', 'kenny', 'cameron', 'declan',
    'otto', 'oliver', 'ejenner', 'dominic', 'pablo', 'mikhail', 'neil', 'owain',
    'aiden', 'gabriel', 'will', 'stanislav', 'mikkel', 'simon', 'karl', 'jimmy',
    'ben', 'cullen', 'jordan', 'igor', 'jonas', 'jacques', 'alvin', 'ronny', 
    'ioannes', 'hauke', 'lee', 'leon', 'joel', 'conor', 'rohan', 'mateusz',
    'tristan', 'vladimir', 'sean', 'sam', 'dalton', 'caleb', 'joe', 'andy',
    'amir', 'euan', 'gabe', 'ivan', 'iwan', 'afred', 'zac', 'nikita', 'vael',
    'nick', 'filip', 'dusan', 'julian', 'max', 'moritz', 'edouard', 'julius',
    'grant', 'marc', 'johann', 'anton', 'matt', 'ig0r', 'tom', 'gregor', 'luke',
    'derek', 'morgan', 'lennart', 'hamish', 'jim', 'matthias', 'everett', 'liam',
    'todd', 'tyrrell', 'jean', 'jaan', 'yonatan', 'geoffrey', 'tomek', 'felix',
    'valentin', 'quentin', 'parker', 'gianluca', 'rahul', 'winston', 'ozzie', 
    'corin', 'lawchan', 'elifland', 'adrian', 'agucova', 'pepe', 'steve', 'aidan',
    'jesse', 'tsvibt', 'raemon', 'vaniver', 'silas', 'rubi', 'jarviniemi', 'olli', 
    'gergo', 'gasteigerjo', 'augustin', 'gentzel', 'soren', 'lsusr', 'gworley', 
    'ruby', 'gwern', 'mingyuan', 'screwtape', 'alkjash', 'yair', 'bhauth', 
    'diffractor', 'hazard', 'charlie', 'remmelt', 'shminux', 'jmh', 'mako',
    'paolo', 'elriggs', 'wei_dai', 'alenglander', 'aphyer', 'lc',
    'liron', 'deluks', 'cousin_it', 'moridinamael', 'scasper', 'ege-erdil', 
    'jsevillamol', 'mtrazzi', 'dadadarren', 'beren', 'jchan', 'bob', 'linch',
    'issa', 'said', 'nostalgebraist', 'vojta', 'pchvykov', 'madhatter', 'q home',
    'whitehatstoic', 'miguel', 'chaosmage', 'm. y. zuo', 'algon', 'raphael',
    'lorec', 'rmoehn', 'roko', 'ulisse', 'casebash', 'curi', 'lrudl', 'devin', 
    'lukas', 'lucas', 'douglas', 'vipul', 'ozyrus', 'gene', 'fowlertm', 'gilch', 
    'eneasz', 'justis', 'joar', 'jelle', 'jeppe', 'kristian', 'dave', 'kabir', 
    'roland', 'andrey', 'tim', 'yaroslav', 'brad', 'brat', 'dan', 'bryan',
    'x4vier', 'xavier', 'tiago', 'rupert', 'vlad', 'vitor', 'tony', 'rishit', 
    'jeremiah', 'akbir', 'jay', 'anson', 'younes', 'francis', 'andre', 'josh', 
    'seb', 'mathias', 'aditya', 'nate', 'nikolay', 'nikolaj', 'yashvardhan', 
    'isaac', 'elijah', 'carter', 'wyatt', 'jayden', 'dylan', 'grayson', 'levi', 
    'mateo', 'jaxon', 'lincoln', 'theodore', 'asher', 'isaiah', 'josiah', 
    'sebastian', 'colton', 'eli', 'landon', 'hudson', 'hunter', 'connor', 
    'santiago', 'jameson', 'axel', 'blake', 'carlos', 'victor', 'oscar', 'marcus', 
    'chase', 'finn', 'cole', 'shane', 'riley', 'austin', 'miles', 'cooper', 
    'bryce', 'emmett', 'preston', 'kai', 'dean', 'ezra', 'ricardo', 'phoenix',
    'raj', 'ravi', 'amit', 'suresh', 'rajesh', 'mahesh', 'ramesh', 'dinesh',
    'krishna', 'arjun', 'rohan', 'vikram', 'sanjay', 'ajay', 'vijay', 'nikhil',
    'arun', 'anand', 'rakesh', 'manish', 'ashish', 'rohit', 'shivam', 'aman',
    'abhishek', 'akash', 'gaurav', 'karan', 'varun', 'vishal', 'sachin', 'rahul',
    'deepak', 'pradeep', 'sunil', 'anil', 'mukesh', 'yogesh', 'naveen', 'pankaj',
    'sandeep', 'vivek', 'vinay', 'sagar', 'tushar', 'hemant', 'lalit', 'kishore',
    'hiroshi', 'takeshi', 'kazuo', 'satoshi', 'masaki', 'yuki', 'kenji', 'daiki',
    'ryota', 'kenta', 'shota', 'yuta', 'ren', 'haruto', 'yuji', 'taro', 'jiro',
    'saburo', 'ichiro', 'goro', 'hachiro', 'kichiro', 'akira', 'makoto', 'osamu',
    'minoru', 'tadashi', 'noboru', 'kaoru', 'mamoru', 'isamu', 'susumu', 'hajime',
    'wei', 'ming', 'jun', 'feng', 'gang', 'lei', 'qiang', 'yong', 'jian', 'bin',
    'peng', 'tao', 'long', 'hao', 'cheng', 'yang', 'fei', 'liang', 'dong', 'xin',
    'xiong', 'rui', 'han', 'chen', 'lin', 'yuan', 'bo', 'kun', 'xiang',
    'zheng', 'yu', 'qin', 'shi', 'guo', 'wang', 'zhang', 'zhao', 'huang', 'zhou',
    'lars', 'erik', 'nils', 'bjorn', 'magnus', 'tor', 'ulf', 'gustav',
    'sven', 'oskar', 'viktor', 'emil', 'ludvig', 'elias', 'hugo', 'isak', 'theo',
    'francesco', 'alessandro', 'lorenzo', 'leonardo', 'matteo', 'gabriele',
    'riccardo', 'giuseppe', 'salvatore', 'vincenzo', 'giovanni', 'michele',
    'franco', 'sergio', 'mario', 'bruno', 'carlo', 'roberto', 'alberto', 'giorgio',
    'pierre', 'michel', 'alain', 'philippe', 'bernard', 'claude', 'gerard',
    'antoine', 'françois', 'sebastien', 'frederic', 'julien', 'laurent', 
    'olivier', 'pascal', 'thierry', 'hans', 'klaus', 'wolfgang', 'manfred', 
    'helmut', 'walter', 'günter', 'dieter', 'jürgen', 'bernd', 'rainer', 'uwe', 
    'werner', 'horst', 'gerhard', 'ralf', 'detlef', 'norbert', 'jens', 'steffen',
    'aleksandr', 'sergey', 'aleksey', 'maxim', 'oleg', 'pavel', 'roman', 'yuriy', 
    'evgeniy', 'denis', 'artem', 'kirill', 'yegor', 'ruslan',
    'val', 'ike', 'fin', 'zane', 'daan', 'fraser', 'tyson', 'lewis', 'russell', 'pinto',
    'sergei', 'hadrien', 'sahil', 'burns', 'mojmir', 'claudio', 'keaton', 'egor',
    'mustafa', 'atharva', 'dinkar', 'aron', 'jude', 'arvo', 'alfred', 'ramon',
    'casey', 'forrest', 'momcilo', 'ahmed', 'graeme', 'russel', 'tegan', 'harjas',
    'woody', 'dex', 'chapin', 'hadrien', 'karthik', 'jeff', 'arturs', 'prince',
    'ihor', 'freddie', 'dmitrii', 'michal', 'parthh', 'jakub', 'anish', 'jake',
    'gideon', 'louka', 'keaton', 'tobi', 'dimi', 'sathish', 'mustafa', 'sezer',
    'kola', 'bart', 'gal', 'wynn', 'aksh', 'satvik', 'diego', 'javier', 'wilson',
    'joao', 'edgar', 'dhruv', 'rome', 'sunishchal', 'saeid', 'lewis', 'vernichtung',
    'enoch', 'curtis', 'edmund', 'carson', 'dustin', 'logan', 'glen', 'omid', 'luis', 
    'harold', 'damien', 'luca', 'jeroen', 'judson', 'allen', 'ace', 'bruce', 'adrià', 
    'moses', 'cedric', 'taymon', 'vincent', 'solomon', 'luigi', 'wdmacaskill', 
    'jasper', 'radford', 'fahad', 'jdcampolargo', 'kaarlo', 'matej', 'raphaëll',
    'rasmus', 'aaguirre', 'szymon', 'artyom', 'onur', 'mathis', 'gytis', 'wulky', 'jorges',
    'sandro', 'jon', 'bernie', 'thor', 'mathieu', 'jotham', 'dorian', 'milo',
    'roven', 'tamay', 'garrett', 'carl', 'kristof', 'jörn', 'lowell', 'domenic', 
    'keith', 'bastiaan', 'bruce', 'brett', 'greg', 'toby', 'rhys', 'curt', 'stepan',
    'harrison', 'nicolas', 'dawson', 'yovel', 'jáchym', 'malte', 'yakov', 'santeri',
    'andrij', 'randall', 'itay', 'maciej', 'pekka', 'pete', 'clément', 'akram', 'eoin',
    'kieron', 'jakob', 'damilo', 'ian', 'nicolo', 'lauriander', 'patrik', 'patrick',
    'edmun', 'vittu', 'marek', 'lucien', 'ewan', 'vorak', 'wes', 'aengus',
    'rick', 'callum', 'avi'
}

FEMALE_NAMES = {
    'mary', 'patricia', 'jennifer', 'linda', 'elizabeth', 'barbara', 'susan',
    'jessica', 'sarah', 'karen', 'nancy', 'lisa', 'betty', 'helen', 'sandra',
    'donna', 'carol', 'ruth', 'sharon', 'michelle', 'laura', 'kimberly',
    'deborah', 'dorothy', 'emily', 'emma', 'madison', 'olivia', 'hannah', 
    'abigail', 'isabella', 'samantha', 'ashley', 'alexis', 'sophia', 'alyssa', 
    'grace', 'ava', 'taylor', 'brianna', 'lauren', 'chloe', 'natalie', 'katherine', 
    'rachel', 'megan', 'anna', 'victoria', 'nicole', 'chelsea', 'stephanie', 
    'courtney', 'amanda', 'danielle', 'brittany', 'jasmine', 'maria', 'sara', 
    'alex', 'andrea', 'katja', 'gram', 'vanessa', 'brienne', 'nina', 'ninell', 
    'eleni', 'lynette', 'julia', 'ariel', 'rose', 'darcy', 'ajeya', 'mathilde',
    'cecilia', 'erin', 'viktoria', 'beatrice', 'natasha', 'holly', 'adele',
    'eva', 'greta', 'gretta', 'camille', 'camilla', 'jacy', 'lizka', 'maia', 
    'maja', 'saskia', 'vika', 'beth', 'vishakha', 'zoe', 'tessa', 'vera', 
    'amy', 'mycah', 'hivewired', 'octavia', 'eukaryote', 'aella', 'marta', 
    'martha', 'nandi', 'jess', 'fabienne', 'rebecca', 'crystal', 'caroline', 
    'janet', 'catherine', 'frances', 'christine', 'debra', 'carolyn', 'virginia', 
    'heather', 'diane', 'julie', 'joyce', 'kelly', 'christina', 'joan', 'evelyn', 
    'judith', 'cheryl', 'jacqueline', 'gloria', 'janice', 'ann', 'kathryn', 
    'teresa', 'doris', 'marie', 'ruby', 'charlotte', 'amelia', 'harper', 'ella', 
    'scarlett', 'riley', 'aria', 'lily', 'aubrey', 'zoey', 'penelope', 'lillian', 
    'addison', 'layla', 'camila', 'brooklyn', 'leah', 'aaliyah', 'savannah', 
    'gabriella', 'claire', 'skylar', 'bella', 'genesis', 'leilani', 'jordan', 
    'jocelyn', 'lyla', 'maggie', 'paige', 'valentina', 'nora', 'cora', 'alice', 
    'elena', 'ivy', 'ellie', 'daisy', 'lucia', 'ainsley', 'austin', 'nova', 
    'parker', 'hunter', 'raven', 'jordyn', 'sage', 'phoenix', 'river', 'dakota', 
    'rowan', 'london', 'eden', 'juniper', 'autumn', 'iris', 'luna', 'willow', 
    'hazel', 'violet', 'aurora', 'poppy', 'maeve', 'kinsley', 'naomi', 'maya', 
    'audrey', 'stella', 'brooke', 'faith', 'hope', 'destiny', 'sydney', 'miranda', 
    'cassandra', 'sierra', 'morgan', 'tiffany', 'sonya', 'alicia', 'jenna', 
    'bethany', 'erica', 'marissa', 'lindsay', 'molly', 'katie', 'shannon', 
    'alexandra', 'katelyn', 'allison', 'haley', 'brittney', 'shelby', 'summer',
    'april', 'diamond', 'pearl', 'jade', 'serena', 'diana', 'athena', 'artemis',
    'venus', 'minerva', 'celia', 'delia', 'fiona', 'gina', 'iona', 'lena',
    'mina', 'tina', 'zara', 'clara', 'flora', 'dora', 'priya', 'ananya',
    'kavya', 'isha', 'arya', 'diya', 'riya', 'sara', 'anya', 'neha', 'pooja',
    'shreya', 'aditi', 'aisha', 'meera', 'tanya', 'divya', 'sanya', 'rhea',
    'nisha', 'sneha', 'swati', 'preeti', 'sunita', 'rekha', 'geeta', 'seema',
    'deepika', 'nandini', 'ragini', 'pallavi', 'shweta', 'manisha', 'rashmi',
    'sapna', 'jyoti', 'usha', 'sushma', 'madhuri', 'anita', 'sita', 'rita',
    'gita', 'mira', 'kira', 'lila', 'maya', 'devi', 'lakshmi', 'saraswati',
    'parvati', 'radha', 'sita', 'ganga', 'yamuna', 'chandra', 'surya', 'tara',
    'akiko', 'yuki', 'sakura', 'hana', 'mei', 'emi', 'aya', 'rina', 'mika',
    'asuka', 'haruka', 'nana', 'kana', 'saki', 'yui', 'rei', 'moe', 'ai',
    'riko', 'yuka', 'maki', 'hitomi', 'jun', 'keiko', 'naomi', 'hiroko',
    'masako', 'fumiko', 'tomoko', 'noriko', 'sachiko', 'michiko', 'yoshiko',
    'li', 'wei', 'xin', 'yan', 'ling', 'min', 'jing', 'hui', 'juan', 'ping',
    'lei', 'fang', 'hong', 'ying', 'qing', 'lan', 'xiao', 'na', 'yun', 'rui',
    'meiling', 'xiaoli', 'xiaofang', 'xiaojuan', 'xiaomin', 'xiaohong', 'xiaolan',
    'ingrid', 'astrid', 'greta', 'helga', 'brigitta', 'margit', 'ursula', 'petra',
    'sabine', 'katarina', 'gabriela', 'monika', 'susanne', 'claudia', 'andrea',
    'silvia', 'martina', 'eva', 'barbara', 'christa', 'doris', 'elfriede',
    'francoise', 'marie', 'isabelle', 'sylvie', 'nathalie', 'catherine', 'christine',
    'monique', 'brigitte', 'nicole', 'veronique', 'sandrine', 'valerie', 'corinne',
    'pascale', 'dominique', 'chantal', 'michele', 'danielle', 'martine', 'laurence',
    'giovanna', 'francesca', 'paola', 'laura', 'barbara', 'elena', 'monica',
    'stefania', 'patrizia', 'roberta', 'claudia', 'rita', 'carla', 'daniela',
    'alessandro', 'manuela', 'simona', 'marina', 'cristina', 'federica', 'chiara',
    'valentina', 'serena', 'ilaria', 'giulia', 'sara', 'alice', 'martina',
    'carmen', 'pilar', 'dolores', 'mercedes', 'josefa', 'francisca', 'antonia',
    'maria', 'teresa', 'ana', 'isabel', 'cristina', 'marta', 'angeles', 'lucia',
    'rosa', 'concepcion', 'amparo', 'manuela', 'remedios', 'esperanza',
    'irina', 'elena', 'natasha', 'svetlana', 'olga', 'tatiana', 'marina',
    'anastasia', 'ekaterina', 'yulia', 'anna', 'maria', 'galina', 'lyudmila',
    'valentina', 'nadezhda', 'larisa', 'vera', 'nina', 'alla', 'tamara',
    'tanja', 'leticiagarcia', 'siya', 'gracie', 'jenny', 'kerry', 'rivka', 
    'maggy', 'nidhi', 'cissy', 'darcey', 'sophie', 'ellen', 'lydia', 'inga', 'sandi',
    'sandy', 'jolly', 'sophie', 'sophia', 'lydia', 'yoreth', 'anca', 'anka',
    'apollonia', 'amber', 'lucy', 

}