# Simple name-to-gender mapping (you can expand this)
MALE_NAMES = {
    '1a3orn', 'a.olmotitos', 'aaguirre', 'aaron', 'abdul', 'abe', 'abhay', 'abhimanyu',
    'abhishaike', 'abhishek', 'abram', 'ace', 'adam', 'adi', 'adithya', 'aditya',
    'adriaan', 'adrian', 'adrien', 'adrià', 'aelwood', 'aengus', 'afred', 'agent smith',
    'agentydragon', 'agucova', 'ahmed', 'aidan', 'aiden', 'ajay', 'ajith', 'akash',
    'akbir', 'akira', 'akram', 'aksh', 'alain', 'alamerton', 'alan', 'albert',
    'alberto', 'aldrin', 'aleksander', 'aleksandr', 'aleksey', 'alenglander', 'alessandro', 'alex',
    'alexander', 'alexei', 'alexis-carlier', 'alexmennen', 'alfonso', 'alfred', 'algon', 'ali',
    'alkjash', 'allen', 'alvaro', 'alvin', 'alx', 'alyosha', 'amadeus', 'aman',
    'amaury', 'amir', 'amit', 'anand', 'anders', 'andre', 'andrei', 'andrew',
    'andrey', 'andrij', 'andy', 'anil', 'anish', 'anmol', 'anshul', 'anson',
    'anthony', 'antoine', 'anton', 'antonio', 'anurag', 'aphyer', 'arash', 'aric',
    'aris', 'arjun', 'arkhos', 'arman', 'arne', 'aron', 'arrrlex', 'artem',
    'arthur', 'artkpv', 'arturo', 'arturs', 'artyom', 'arun', 'arvo', 'ash-jafari',
    'asher', 'ashish', 'ashwin', 'asksathvik', 'atharva', 'augustin', 'avi', 'axel',
    'aydin', 'azsantosk', 'balazs', 'baram', 'barry', 'bart', 'bastiaan', 'ben',
    'benjamin', 'benjaminfrank', 'bence', 'bensomething', 'beny', 'bernie', 'bernard', 'beren',
    'berta', 'bharath', 'bhauth', 'bian', 'biden', 'biff', 'bill', 'billy', 'blake',
    'bob', 'bobby', 'bogdan', 'boaz', 'bond', 'boris', 'brad', 'brandon', 'brat',
    'bree', 'bren', 'brenton', 'brian', 'brice', 'bridget', 'bruno', 'bryan',
    'bryce', 'buck', 'buddha', 'bure', 'burt', 'cad', 'caden', 'cade',
    'caf', 'caleb', 'callum', 'carl', 'carlos', 'carson', 'casebash', 'casey',
    'cedric', 'cedr', 'cedu', 'cedu2', 'cel', 'chad', 'charlie', 'charles',
    'chase', 'chetan', 'chico', 'chris', 'christian', 'christopher', 'clark', 'claude',
    'cole', 'colin', 'connall', 'conor', 'cons', 'corey', 'cory', 'cousin_it',
    'craig', 'curi', 'curtis', 'cush', 'dagon', 'dai', 'dale', 'dalton',
    'dan', 'dana', 'danial', 'daniel', 'danilo', 'danny', 'darius', 'darren',
    'david', 'davide', 'davis', 'dawson', 'dd', 'dean', 'declan', 'derek',
    'des', 'devin', 'dex', 'dhruv', 'dick', 'diego', 'dimitri', 'dimi',
    'dimin', 'dingle', 'dino', 'dinesh', 'dinoo', 'dior', 'dmitrii', 'dmitry',
    'domin', 'dominik', 'dominic', 'domenic', 'doran', 'dorian', 'dost', 'douglas',
    'down', 'dref', 'drew', 'dud', 'dude', 'duncan', 'dustin', 'dva',
    'ed', 'edgar', 'edmund', 'edouard', 'eduardo', 'eel', 'ef', 'eg',
    'egor', 'eigen', 'eiko', 'elias', 'eli', 'elijah', 'elmer', 'elo',
    'elriggs', 'emil', 'emmett', 'emrik', 'emre', 'emre-2', 'em', 'ence',
    'enoch', 'enrique', 'ente', 'epirito', 'eric', 'erland', 'ernest', 'erwan',
    'esben', 'esrogs', 'ese', 'et', 'ethan', 'euan', 'euler', 'evar',
    'everett', 'ewan', 'fahad', 'faisal', 'fay', 'federico', 'felix', 'finn',
    'fin', 'finnbar', 'forrest', 'francesco', 'francis', 'françois', 'frank',
    'fred', 'freddie', 'frederic', 'fritz', 'fritz2', 'frod', 'fsh', 'fsk',
    'gabriel', 'gabe', 'gal', 'garrett', 'garrison', 'gaston', 'gaurav', 'gavin',
    'geoffrey', 'geoff', 'gene', 'georg', 'george', 'gerard', 'gergo', 'gilch',
    'gino', 'giorgio', 'glen', 'gob', 'god', 'goeran', 'gordon', 'gost',
    'gou', 'grady', 'gray', 'greg', 'gregor', 'gri', 'groot', 'gus',
    'gustav', 'gwern', 'gworley', 'guy', 'hadrien', 'hajime', 'hamish', 'harold',
    'harjas', 'harr', 'harrison', 'harry', 'hashem', 'haze', 'hazard', 'hendrik',
    'henk', 'henry', 'herman', 'heramb', 'hesh', 'hib', 'hjalmar', 'hiroshi',
    'hugh', 'hug', 'hugo', 'huon', 'husky', 'huw', 'ia', 'ibn',
    'ichiro', 'igor', 'ig0r', 'ike', 'il', 'ilia', 'ilya', 'iman',
    'im', 'imad', 'imam', 'imran', 'indra', 'ioannes', 'ion', 'iwan',
    'ivan', 'iz', 'izzy', 'ja', 'jab', 'jack', 'jackson', 'jacob',
    'jacques', 'jaden', 'jaf', 'jake', 'jamal', 'james', 'jameson', 'jamey',
    'jared', 'jarviniemi', 'jason', 'jaspar', 'javier', 'jay', 'jayden', 'jayesh',
    'jb', 'jce', 'jd', 'jdcampolargo', 'jean', 'jeff', 'jeffrey', 'jell',
    'jelle', 'jensen', 'jeremiah', 'jeremias', 'jeremy', 'jerry', 'jesse', 'jett',
    'jgm', 'jhm', 'jimbo', 'jim', 'jimmy', 'jmh', 'jms', 'jo',
    'joacim', 'joao', 'joar', 'joel', 'johann', 'johannes', 'john', 'johnny',
    'jon', 'jonah', 'jonathan', 'jonatan', 'jonas', 'jordan', 'jose', 'joseph',
    'josh', 'joshua', 'jovan', 'jow', 'judge', 'judson', 'juan', 'jub',
    'jude', 'judy', 'jules', 'julius', 'julian', 'juro', 'justis', 'justin',
    'jwray', 'kac', 'kadir', 'kai', 'kale', 'kan', 'kabir', 'karl',
    'karel', 'kast', 'kave', 'kazan', 'kazuo', 'keaton', 'keith', 'ken',
    'kenn', 'kenny', 'kenji', 'keo', 'kepler', 'kieron', 'kieran', 'kingsley',
    'king', 'kirill', 'kishore', 'kla', 'klaud', 'klas', 'klaudio', 'kl',
    'kola', 'kolya', 'kon', 'kongo', 'koen', 'kor', 'kory', 'kosta',
    'kristian', 'kristof', 'kristopher', 'kris', 'krishaan', 'krist', 'krzysztof', 'kumar',
    'kurt', 'kyle', 'la', 'lab', 'lach', 'lad', 'lael', 'laet',
    'lah', 'lair', 'lamb', 'lance', 'landon', 'lane', 'lang', 'larry',
    'laurence', 'lauriander', 'laurent', 'laur', 'lazar', 'le', 'lead', 'leif',
    'leif wenar', 'leifwenar', 'leifw', 'lej', 'leon', 'leonard', 'leonardo', 'le-nguyen-hoang',
    'lev', 'levi', 'lia', 'liam', 'libai', 'linch', 'lind', 'linus',
    'lionel', 'lisa', 'lito', 'lites', 'liver', 'lloyd', 'lodewijk', 'loic',
    'loic-cabannes', 'lolo', 'london', 'lon', 'lone', 'long', 'lor', 'lorance',
    'lorenzo', 'louka', 'louis', 'luca', 'lucas', 'lucien', 'ludvig', 'lukas',
    'luke', 'luigi', 'luis', 'luka', 'lund', 'ly', 'm. y. zuo', 'mabel',
    'maciej', 'mako', 'malte', 'malcolm', 'manfred', 'manish', 'maralorn', 'marc',
    'marco', 'marcus', 'marek', 'mario', 'marius', 'mark', 'martin', 'marvin',
    'masaki', 'mason', 'matej', 'mateo', 'mateusz', 'matheus', 'mathias', 'mathieu',
    'mathijs', 'mathis', 'matt', 'matteo', 'matthew', 'matthias', 'mauricio', 'mauro',
    'max', 'maxim', 'maxwell', 'meir', 'mergimio', 'mgfcatherall', 'michael', 'michal',
    'michał', 'michel', 'michele', 'mickey', 'miguel', 'mike', 'mikhail', 'mikkel',
    'miles', 'milo', 'milton', 'ming', 'mingyuan', 'minoru', 'mislav', 'mister',
    'mitchell', 'mo', 'mohammad', 'mojmir', 'momcilo', 'mondsemmel', 'morgan', 'moridinamael',
    'moritz', 'moses', 'moshe', 'mostafa', 'moyamo', 'mr', 'mr-beastly', 'mr.magpie',
    'mridul', 'mrmind', 'mrpointy', 'mtrazzi', 'mukesh', 'munkh', 'mustafa', 'mwatkins',
    'nate', 'nathan', 'naveen', 'neel', 'neil', 'nguyen-tran', 'nicholas', 'nick',
    'niclas', 'nicolas', 'nicolo', 'niel', 'nikhil', 'nikita', 'niko', 'nikolai',
    'nikolaj', 'nikolay', 'nils', 'nitin', 'noah', 'noboru', 'norbert', 'norman',
    'nostalgebraist', 'ofer', 'ojorgensen', 'olaoluwa', 'ole', 'oleg', 'oliver',
    'olivier', 'olli', 'omar', 'omid', 'ondrej', 'onur', 'oren', 'orfeas',
    'orpheus', 'oscar', 'oskar', 'osman', 'ovidijus', 'owain', 'owen', 'ozzie',
    'ozyrus', 'pankaj', 'paolo', 'parth', 'parthh', 'pasha', 'pat', 'pavel',
    'pavle', 'paul', 'pedro', 'pepe', 'pete', 'peter', 'phil', 'philippe',
    'philip', 'piotr', 'pl5015', 'pog', 'polo', 'pradeep', 'prance', 'pravin', 'preston',
    'prince', 'quinn', 'quentin', 'quintin', 'rafael', 'raphael', 'raphaëll', 'raemon',
    'rakesh', 'ram', 'ramesh', 'ramon', 'ram@rachum.com', 'ramp', 'randall', 'randy',
    'raoul', 'rap', 'rash', 'rashid', 'rasmus', 'raul', 'ray', 'raymond', 'raz',
    'razmęk', 're', 'reece', 'reg', 'rem', 'remmelt', 'remmelt-ellen', 'ren',
    'renato', 'reno', 'reuben', 'rex', 'ricard', 'ricardo', 'rich', 'richard',
    'rick', 'rider', 'riley', 'riley2', 'rishi', 'rishit', 'rishub', 'rishubjain',
    'rithvik', 'rival', 'rob', 'robert', 'roberto', 'robin', 'rohan', 'rohin',
    'rok', 'roko', 'roland', 'roman', 'rome', 'ron', 'ronak', 'ronen', 'roney',
    'ronny', 'roven', 'roy', 'rud', 'rudi', 'rudolf', 'rupert', 'russ', 'russel',
    'russell', 'ruth', 'ryan', 'ryan-carey', 'ryen', 'saburo', 'sachin', 'safi',
    'saeid', 'sahil', 'saif', 'saint', 'saj', 'saketh', 'salah', 'salvatore',
    'sam', 'samba', 'sammy', 'samuel', 'sandeep', 'sandor', 'santiago', 'sanjay',
    'sant', 'santiago2', 'saq', 'sarb', 'saul', 'sav', 'seb', 'sebastian',
    'sean', 'seba', 'sebastien', 'sezer', 'seth', 'shaan', 'shaed', 'shain',
    'shaka', 'sham', 'shamim', 'shawn', 'shiva', 'shivam', 'shminux', 'shoaib',
    'shoka', 'shota', 'sid', 'sidhu', 'sidney', 'simon', 'simonj', 'simonk',
    'siri', 'sitaram', 'sk', 'skinner', 'skivverus', 'sl', 'slav', 'sly',
    'solomon', 'sou', 'soumyadeep', 'soumy', 'spencer', 'stan', 'stanislav', 'stefan',
    'steffen', 'stephen', 'stephenj', 'steve', 'steven', 'stijn', 'stone', 'stp',
    'stuart', 'sud', 'sudhanshu', 'suleiman', 'sultan', 'sur', 'suresh', 'sven',
    'syl', 'szymon', 'tadashi', 'tamer', 'tang', 'tarek', 'taylor', 'taylor2', 'taz',
    'tazman', 'tbone', 'taylor3', 'ted', 'terence', 'terry', 'thaddeus', 'thales',
    'theo', 'theodore', 'thiccythot', 'thor', 'thomas', 'tibor', 'tigran', 'tim',
    'timothy', 'timon', 'tino', 'titus', 'tobias', 'tob', 'toby', 'todd',
    'toni', 'tony', 'tom', 'tommy', 'tomek', 'tony2', 'tor', 'tore', 'torr',
    'tosh', 'tra', 'travis', 'trent', 'trevor', 'tri', 'tristan', 'trumpet', 'tsetse',
    'tuf', 'tufan', 'turgut', 'turntrout', 'tushar', 'tuy', 'tv', 'tze',
    'uar', 'udo', 'uj', 'uly', 'um', 'umar', 'ur', 'us', 'vassil',
    'val', 'valentin', 'valerii', 'vasko', 'vass', 'vassilije', 'ved', 'vega',
    'vel', 'vernichtung', 'vernon', 'vince', 'vincent', 'vikram', 'vil', 'viktor',
    'vinay', 'vir', 'vlad', 'vladislav', 'vladimir', 'vitor', 'vittorio', 'vj',
    'vlad', 'vladl', 'voro', 'voss', 'vul', 'walter', 'warren', 'wayne',
    'wes', 'west', 'weston', 'whit', 'wick', 'wilf', 'will', 'william', 'wilson',
    'wilm', 'woody', 'wulky', 'wyatt', 'x4vier', 'xander', 'xavier', 'xp',
    'xodarap', 'yair', 'yakov', 'yan', 'yann', 'yash', 'yashvardhan', 'yaakov',
    'yegor', 'yoav', 'youssef', 'yovel', 'yuan', 'yuji', 'yuki', 'yuta',
    'yves', 'zack', 'zach', 'zachary', 'zane', 'zoltan', 'zvi'
}


FEMALE_NAMES = {
    'aaliyah', 'abigail', 'addison', 'adele', 'aditi', 'adriana', 'adrusi', 'aelita',
    'aella', 'ainsley', 'aisha', 'ajeya', 'akiko', 'alena', 'alessandro', 'alexandra',
    'alexis', 'ali', 'alice', 'alicia', 'alina', 'alisha', 'alison', 'alla',
    'allison', 'alma', 'alyssa', 'amanda', 'amber', 'amelia', 'amparo', 'amy',
    'ana', 'anabel', 'ananya', 'anastasia', 'anastasiya', 'anca', 'andrea', 'angela',
    'angeles', 'anita', 'anka', 'ann', 'anna', 'anne', 'antonia', 'anya',
    'apollonia', 'april', 'arden', 'aria', 'ariel', 'arithine', 'artemis', 'arya',
    'asha', 'ashley', 'astrid', 'asuka', 'athena', 'aubrey', 'audrey', 'aurora',
    'autumn', 'ava', 'avanti', 'aya', 'aysja', 'barbara', 'beatrice', 'becky',
    'bella', 'beth', 'bethany', 'betty', 'brianna', 'bridgett', 'brienne', 'brigitta',
    'brigitte', 'britt', 'brittany', 'brittney', 'brooke', 'brooklyn', 'camila', 'camilla',
    'camille', 'carla', 'carmen', 'carol', 'caroline', 'carolyn', 'cassandra', 'catherine',
    'cecilia', 'celeste', 'celia', 'chana', 'chandra', 'chantal', 'chantiel', 'charlotte',
    'chelsea', 'cheryl', 'chi', 'chiara', 'chloe', 'christa', 'christina', 'christine',
    'cissy', 'claire', 'clara', 'claudia', 'concepcion', 'cora', 'corinne', 'courtney',
    'cristina', 'crystal', 'daisy', 'dakota', 'daniela', 'danielle', 'daphne', 'darcey',
    'darcy', 'daria', 'debbie', 'deborah', 'debra', 'deepika', 'delia', 'destiny',
    'devi', 'diamond', 'diana', 'diane', 'divya', 'diya', 'dolores', 'dominique',
    'donna', 'dora', 'doris', 'dorothy', 'eden', 'ekaterina', 'elena', 'eleni',
    'elfriede', 'elika', 'elizabeth', 'ella', 'ellen', 'ellie', 'emi', 'emily',
    'emma', 'epiphi', 'erica', 'erin', 'esperanza', 'eukaryote', 'eva', 'evelyn',
    'fabienne', 'faith', 'fang', 'federica', 'fiona', 'flora', 'frances', 'francesca',
    'francisca', 'francoise', 'franziska', 'fumiko', 'gabby', 'gabi', 'gabriela', 'gabriella',
    'galina', 'ganga', 'geeta', 'genesis', 'gina', 'girl', 'gloria', 'grace',
    'gracie', 'gram', 'greta', 'gretta', 'hallie', 'hana', 'harper', 'hazel',
    'heather', 'helen', 'helga', 'hivewired', 'holly', 'hong', 'hope', 'hunter',
    'iana', 'ida', 'ines', 'inga', 'ingrid', 'iona', 'irina', 'iris',
    'isabel', 'isabella', 'isabelle', 'isha', 'ivy', 'jacqueline', 'jacy', 'jade',
    'jane', 'janet', 'janice', 'jasmine', 'jenn', 'jenna', 'jennifer', 'jenny',
    'jess', 'jessica', 'joan', 'joanna', 'joanne', 'jocelyn', 'jodie', 'joyce',
    'judith', 'julia', 'julian', 'julija', 'julie', 'jun', 'juniper', 'jyoti',
    'karen', 'karina', 'kate', 'katelyn', 'katherine', 'katharine', 'kathryn', 'kathy',
    'katrina', 'katalina', 'katja', 'katy', 'kavya', 'kelly', 'kerry', 'keiko',
    'kinsley', 'kira', 'kirsten', 'kseniya', 'ksenia', 'lady', 'lara', 'laura',
    'lauren', 'laurie', 'layla', 'leah', 'leilani', 'lena', 'leticiagarcia', 'lilly',
    'lila', 'lillian', 'lily', 'lindsay', 'ling', 'lisa', 'liz', 'lizka',
    'lizzie', 'liza', 'lucia', 'lucy', 'lulie', 'luna', 'lydia', 'lyla',
    'lynette', 'madi_hexa', 'maeve', 'maia', 'maja', 'makayla', 'mala', 'malka',
    'margaret', 'margit', 'marie', 'marianne', 'marina', 'marissa', 'marisol', 'marta',
    'martha', 'martina', 'marya', 'mary', 'math-viking', 'mathilde', 'maya', 'meera',
    'meg', 'megan', 'mei', 'meiling', 'melanie', 'mercedes', 'mia', 'michele',
    'michelle', 'michiko', 'mika', 'mina', 'minerva', 'miranda', 'miss', 'missmarble',
    'moe', 'molly', 'mom', 'monica', 'monique', 'monika', 'mya', 'mycah',
    'nadia', 'nadezhda', 'nandi', 'naomi', 'natalia', 'natasha', 'nathalie', 'neha',
    'nidhi', 'nina', 'ninell', 'nisha', 'noa', 'nora', 'noriko', 'nova', 'octavia',
    'oksana', 'olga', 'olivia', 'oxana', 'paige', 'pallavi', 'parvati', 'paola',
    'patrizia', 'patricia', 'pascale', 'pearl', 'penelope', 'petra', 'phoenix', 'pilar',
    'ping', 'pippa', 'polina', 'pooja', 'poppy', 'preeti', 'priya', 'queen',
    'radha', 'ragini', 'rachel', 'raven', 'rebecca', 'rei', 'rekha', 'remedios',
    'rhea', 'ria', 'riya', 'rivka', 'rina', 'rita', 'riko', 'river', 'rosa',
    'rose', 'rosie', 'rowan', 'ruby', 'sachiko', 'saga', 'sage', 'sabine',
    'sally', 'samantha', 'sana', 'sandra', 'sandy', 'sara', 'sarah', 'sarita',
    'saskia', 'sashika', 'savannah', 'scarlett', 'seema', 'serena', 'sevde',
    'shannon', 'sharon', 'shelby', 'shreya', 'shweta', 'sierra', 'silvia', 'simona',
    'sindhu', 'sinem', 'sita', 'siya', 'skylar', 'sneha', 'sofia', 'sofya',
    'sonata', 'sonya', 'sophia', 'sophie', 'stefania', 'stella', 'stephanie', 'sue',
    'summer', 'sunita', 'surya', 'susan', 'susanne', 'sushma', 'suzie', 'svetlana',
    'swati', 'sydney', 'sylvie', 'tamara', 'tamera', 'tanja', 'tanya', 'tara',
    'tatiana', 'tatjana', 'tatyana', 'taylor', 'teresa', 'tessa', 'tiffany', 'tina',
    'tomoko', 'tricia', 'trish', 'ulyana', 'ursula', 'usha', 'valentina', 'valeria',
    'valerie', 'valeriya', 'vanessa', 'venus', 'vera', 'veronique', 'vicky', 'victoria',
    'vika', 'viktoria', 'violet', 'virginia', 'vishakha', 'wei', 'willow', 'xiaofang',
    'xiaohong', 'xiaojuan', 'xiaolan', 'xiaoli', 'xiaomin', 'xin', 'yamuna', 'ying',
    'yoreth', 'yoshiko', 'yui', 'yuka', 'yuki', 'yulia', 'zara', 'zershaaneh',
    'zia', 'ziz', 'zoe', 'zoey'
}
